version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/deploy/
hooks:
  BeforeInstall:
    - location: Scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: Scripts/download_dumble.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/install.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: Scripts/after_install.sh
      timeout: 300
      runas: root
